# Constants used while sending requests.

WRONG_DATA = -1
OK = 0
CONNECTION_PROBLEM = 1
EMPTY_OPTION = 0
WAIT_NEW_SENDING = 1
WAIT_CONTINUE_SENDING = 2
STOP_SENDING = 3

MAX_REQUESTS_PER_MINUTE = 1000000
